# Usar una imagen base de nginx
FROM nginx:stable-alpine

# Copiar todos los archivos del frontend a la carpeta predeterminada de Nginx
COPY . /usr/share/nginx/html

# Exponer el puerto 80 para acceder al frontend
EXPOSE 80
